# Generated by Django 3.0.6 on 2020-05-22 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.IntegerField()),
                ('admission_date', models.DateField()),
                ('demission_date', models.DateField()),
                ('leader', models.BooleanField()),
                ('leader_name', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('registration', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('extra_hour', models.FloatField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Sector')),
                ('sub_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.SubSector')),
            ],
        ),
    ]
