# Generated by Django 3.0.6 on 2020-05-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_employee_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='demission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
