# Generated by Django 3.0.6 on 2020-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200529_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='extra_hour',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
