# Generated by Django 3.0.6 on 2020-05-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200529_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistory',
            name='created_at',
            field=models.CharField(max_length=50),
        ),
    ]
