# Generated by Django 3.0.6 on 2020-06-03 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_limithour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedhour',
            name='made_by',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='releasedhour',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releasedhours', to=settings.AUTH_USER_MODEL),
        ),
    ]
