# Generated by Django 3.0.6 on 2020-06-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_emplo_schedu_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplo_schedu',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Employee'),
        ),
    ]
