# Generated by Django 3.0.6 on 2020-06-08 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20200606_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sector',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Sector'),
        ),
    ]
