# Generated by Django 3.0.6 on 2020-06-08 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20200608_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplo_schedu',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Employee'),
        ),
    ]
