# Generated by Django 3.0.6 on 2020-06-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20200608_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsector',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
