# Generated by Django 3.0.6 on 2020-06-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20200608_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplo_schedu',
            name='authorized',
            field=models.BooleanField(default=True),
        ),
    ]
