# Generated by Django 3.0.7 on 2020-07-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_emplo_schedu_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='time_limit',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
